import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { FinancialSummary, EXPENSE_CATEGORIES, CATEGORY_COLORS, IncomeEntry, ExpenseEntry } from '@/types/finance';

export function generatePDFReport(
  summary: FinancialSummary,
  incomes: IncomeEntry[],
  expenses: ExpenseEntry[]
): void {
  const doc = new jsPDF();
  const currentMonth = new Date().toLocaleDateString('en-US', { 
    month: 'long', 
    year: 'numeric' 
  });
  
  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(value);
  };

  const formatPercent = (value: number) => `${value.toFixed(1)}%`;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(20, 184, 166); // Primary teal color
  doc.text('Monthly Finance Report', 20, 25);
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(currentMonth, 20, 35);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 42);

  // Summary Section
  doc.setFontSize(16);
  doc.setTextColor(40, 40, 40);
  doc.text('Financial Summary', 20, 60);

  const summaryData = [
    ['Total Income', formatCurrency(summary.totalIncome)],
    ['Total Expenses', formatCurrency(summary.totalExpenses)],
    ['Net Investment', formatCurrency(summary.totalInvestment)],
    ['Spent Percentage', formatPercent(summary.spentPercentage)],
    ['Invested Percentage', formatPercent(summary.investedPercentage)],
  ];

  autoTable(doc, {
    startY: 65,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'striped',
    headStyles: { fillColor: [20, 184, 166] },
    styles: { fontSize: 11 },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
  });

  // Income Section
  const incomeStartY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(16);
  doc.setTextColor(40, 40, 40);
  doc.text('Income Sources', 20, incomeStartY);

  const incomeData = incomes.map(income => [
    income.source,
    income.type,
    formatCurrency(income.amount),
  ]);

  autoTable(doc, {
    startY: incomeStartY + 5,
    head: [['Source', 'Type', 'Amount']],
    body: incomeData,
    theme: 'striped',
    headStyles: { fillColor: [34, 197, 94] }, // Green for income
    styles: { fontSize: 10 },
    columnStyles: { 2: { halign: 'right' } },
  });

  // Expenses by Category Section
  const categoryStartY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(16);
  doc.setTextColor(40, 40, 40);
  doc.text('Expenses by Category', 20, categoryStartY);

  const categoryData = EXPENSE_CATEGORIES
    .filter(cat => summary.expensesByCategory[cat] > 0)
    .sort((a, b) => summary.expensesByCategory[b] - summary.expensesByCategory[a])
    .map(cat => {
      const amount = summary.expensesByCategory[cat];
      const percentage = summary.totalExpenses > 0 
        ? (amount / summary.totalExpenses) * 100 
        : 0;
      return [cat, formatCurrency(amount), formatPercent(percentage)];
    });

  autoTable(doc, {
    startY: categoryStartY + 5,
    head: [['Category', 'Amount', '% of Total']],
    body: categoryData,
    theme: 'striped',
    headStyles: { fillColor: [239, 68, 68] }, // Coral for expenses
    styles: { fontSize: 10 },
    columnStyles: { 
      1: { halign: 'right' },
      2: { halign: 'right' },
    },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'Generated by Monthly Closure Tool',
      20,
      doc.internal.pageSize.height - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 30,
      doc.internal.pageSize.height - 10
    );
  }

  // Save the PDF
  const fileName = `monthly-report-${currentMonth.toLowerCase().replace(' ', '-')}.pdf`;
  doc.save(fileName);
}
